

### get
GET  http://localhost:8000/add


### post product

POST http://localhost:8000/add
Content-Type: application/json
    
    {
        "task": "inactive",
        "desc": "product2"
    }




### register login

POST http://localhost:8000/reg-login
Content-Type: application/json
    
    {
        "fName": "John",
        "lName": "Doe",
        "phone":"123123",
        "email": "abc@gamil.cop",
        "password": "123456",
        "address": "123 abc street",

    }


